---
title: "The Unilateralist’s Curse – Summary and Commentary"
author: "David Laing"
date: '2016-12-31'
output: github_document
---

Imagine it's the year 2070, and among the thousands of computer scientists in the world, there are now ten who have independently figured out how to create an artificial general intelligence (AGI). None of them have gone ahead with it yet. They're all trying to ascertain whether such a development would be good or bad for humanity.

Each of these ten researchers is familiar with the intricate difficulties of the [control problem](https://en.wikipedia.org/wiki/AI_control_problem), and each of them believes they may have made enough headway on it that the AGI could be created safely. But none of them are 100% certain that their specifications are perfect. So they must all weigh the potential consequences of a) creating a misalligned AGI, or b) delaying their own best attempt at an alligned AGI, with the risk that someone else will try first but fail catastrophically.

Let's say none of them have quite solved the control problem, and thus if any one of them goes through with the initiative, the consequences will be harmful. Crowds are smart, and the average judgment of the value of creating the AGI will probably be correct. But there is some variance in these judgments, and if the variance is large enough, there may be one or two researchers who incorrectly decide to proceed.

```{r ai_vis, echo = FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
set.seed(6)
judgments <- rnorm(n = 10, mean = -1, sd = 0.6)
people <- c("Alice", "Bob", "Charlie", "Dan", "Erin", "Frank", "Grace", "Heidi", "Irene", "Jerry")
unil_data <- data.frame(person = people, judgment = judgments)
ggplot(data = unil_data) + 
        geom_point(aes(x = person, y = judgment), stat = "identity", shape = 19, size = 5) +
        coord_flip() +
        geom_hline(yintercept = -1, color = "black") +
        geom_hline(yintercept = 0, color = "red") + theme(plot.subtitle = element_text(vjust = 1), 
    plot.caption = element_text(vjust = 1)) +labs(title = "Will the AGI be created?", 
    x = "Researcher", y = "Judgment of the value of creating the AGI") +
        geom_text(aes(label = "True value ->", x = 10, y = -1.21)) +
        geom_text(aes(label = "Threshold at which", x = 10, y = -0.34)) +
        geom_text(aes(label = "the AGI is created ->", x = 9.5, y = -0.31))
```

This is an example the *unilateralist's curse*, a phenomemon described in a [2016 paper](http://dx.doi.org/10.1080/02691728.2015.1108373) by Nick Bostrom, Thomas Douglas, and Anders Sandberg. The curse occurs when...

- There is a group of altruistic decision-makers.
- Each of them must independently decide whether to undertake a given initiative.
- The value of the initiative is ambiguous; that is, there is some variance in people's judgments of the initiative's value.
- The true value of the initiative is negative.

The curse is that the average judgment of the value of the initiative doesn't determine whether the initiative will be undertaken; instead, the *maximally positive* judgment does. All that is required for the initiative to be undertaken is for a single agent to decide that it would do some good. And there are three potential conditions that could lead to this:

- The variance of the judgments is especially high, causing some agents to make positive judgments regardless of the true value or the average judgment thereof.
- The average judgment is especially close to zero (i.e. neutral — the initiative does neither harm nor good).
- There are especially many agents making the judgment of whether or not to undertake the initiative, causing the tails of the distribution to be filled out.

To mitigate the unilateralist's curse, the authors propose a Principle of Conformity, which urges unilateral decision-makers to defer to the majority opinion about the value of an initiative. In other words, if you're the only person who thinks something is a good (or bad) idea, there's a good chance you're wrong.

The proposed model for the unilateralist's curse is reasonable for perfect Bayesian agents, or perhaps for certain types of organizations, but I believe it lacks some realism about human psychology. For example, I predict that on many issues, human judgment of the value of a given initiative would be bimodal, not Gaussian. It's much more natural and much more common to define oneself as decidedly for or against a proposal than to confidently assert one's uncertainty. Moreover, these judgments are likely to be determined less by the true value of the initiative than by heuristics and biases, many of which will favour either conformity or contrarianism to begin with. So, a Principle of Conformity may simply amplify epistemic irrationality.